// Auto-generated by OpenLane
module soc_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  output uart_tx,
  input uart_rx,
  output spi_sclk,
  output spi_mosi,
  input spi_miso,
  output spi_cs,
  output i2c_scl,
  output i2c_sda_out,
  input i2c_sda_in,
  input[7:0] gpio_in,
  output[7:0] gpio_out,
  output timer_irq,
  output[63:0] mac_result,
  output mac_done
);
endmodule
