/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module soc_top(clk, rst, uart_tx, uart_rx, spi_sclk, spi_mosi, spi_miso, spi_cs, i2c_scl, i2c_sda_out, i2c_sda_in, gpio_in, gpio_out, timer_irq, mac_result, mac_done);
  input clk;
  wire clk;
  input [7:0] gpio_in;
  wire [7:0] gpio_in;
  output [7:0] gpio_out;
  wire [7:0] gpio_out;
  output i2c_scl;
  wire i2c_scl;
  input i2c_sda_in;
  wire i2c_sda_in;
  output i2c_sda_out;
  wire i2c_sda_out;
  output mac_done;
  wire mac_done;
  output [63:0] mac_result;
  wire [63:0] mac_result;
  input rst;
  wire rst;
  output spi_cs;
  wire spi_cs;
  input spi_miso;
  wire spi_miso;
  output spi_mosi;
  wire spi_mosi;
  output spi_sclk;
  wire spi_sclk;
  output timer_irq;
  wire timer_irq;
  input uart_rx;
  wire uart_rx;
  output uart_tx;
  wire uart_tx;
  sky130_fd_sc_hd__conb_1 _00_ (
    .LO(mac_result[0])
  );
  sky130_fd_sc_hd__conb_1 _01_ (
    .LO(mac_result[1])
  );
  sky130_fd_sc_hd__conb_1 _02_ (
    .LO(mac_result[2])
  );
  sky130_fd_sc_hd__conb_1 _03_ (
    .LO(mac_result[3])
  );
  sky130_fd_sc_hd__conb_1 _04_ (
    .LO(mac_result[4])
  );
  sky130_fd_sc_hd__conb_1 _05_ (
    .LO(mac_result[5])
  );
  sky130_fd_sc_hd__conb_1 _06_ (
    .LO(mac_result[6])
  );
  sky130_fd_sc_hd__conb_1 _07_ (
    .LO(mac_result[7])
  );
  sky130_fd_sc_hd__conb_1 _08_ (
    .LO(mac_result[8])
  );
  sky130_fd_sc_hd__conb_1 _09_ (
    .LO(mac_result[9])
  );
  sky130_fd_sc_hd__conb_1 _10_ (
    .LO(mac_result[10])
  );
  sky130_fd_sc_hd__conb_1 _11_ (
    .LO(mac_result[11])
  );
  sky130_fd_sc_hd__conb_1 _12_ (
    .LO(mac_result[12])
  );
  sky130_fd_sc_hd__conb_1 _13_ (
    .LO(mac_result[13])
  );
  sky130_fd_sc_hd__conb_1 _14_ (
    .LO(mac_result[14])
  );
  sky130_fd_sc_hd__conb_1 _15_ (
    .LO(mac_result[15])
  );
  sky130_fd_sc_hd__conb_1 _16_ (
    .LO(mac_result[16])
  );
  sky130_fd_sc_hd__conb_1 _17_ (
    .LO(mac_result[17])
  );
  sky130_fd_sc_hd__conb_1 _18_ (
    .LO(mac_result[18])
  );
  sky130_fd_sc_hd__conb_1 _19_ (
    .LO(mac_result[19])
  );
  sky130_fd_sc_hd__conb_1 _20_ (
    .LO(mac_result[20])
  );
  sky130_fd_sc_hd__conb_1 _21_ (
    .LO(mac_result[21])
  );
  sky130_fd_sc_hd__conb_1 _22_ (
    .LO(mac_result[22])
  );
  sky130_fd_sc_hd__conb_1 _23_ (
    .LO(mac_result[23])
  );
  sky130_fd_sc_hd__conb_1 _24_ (
    .LO(mac_result[24])
  );
  sky130_fd_sc_hd__conb_1 _25_ (
    .LO(mac_result[25])
  );
  sky130_fd_sc_hd__conb_1 _26_ (
    .LO(mac_result[26])
  );
  sky130_fd_sc_hd__conb_1 _27_ (
    .LO(mac_result[27])
  );
  sky130_fd_sc_hd__conb_1 _28_ (
    .LO(mac_result[28])
  );
  sky130_fd_sc_hd__conb_1 _29_ (
    .LO(mac_result[29])
  );
  sky130_fd_sc_hd__conb_1 _30_ (
    .LO(mac_result[30])
  );
  sky130_fd_sc_hd__conb_1 _31_ (
    .LO(mac_result[31])
  );
  sky130_fd_sc_hd__conb_1 _32_ (
    .LO(mac_result[32])
  );
  sky130_fd_sc_hd__conb_1 _33_ (
    .LO(mac_result[33])
  );
  sky130_fd_sc_hd__conb_1 _34_ (
    .LO(mac_result[34])
  );
  sky130_fd_sc_hd__conb_1 _35_ (
    .LO(mac_result[35])
  );
  sky130_fd_sc_hd__conb_1 _36_ (
    .LO(mac_result[36])
  );
  sky130_fd_sc_hd__conb_1 _37_ (
    .LO(mac_result[37])
  );
  sky130_fd_sc_hd__conb_1 _38_ (
    .LO(mac_result[38])
  );
  sky130_fd_sc_hd__conb_1 _39_ (
    .LO(mac_result[39])
  );
  sky130_fd_sc_hd__conb_1 _40_ (
    .LO(mac_result[40])
  );
  sky130_fd_sc_hd__conb_1 _41_ (
    .LO(mac_result[41])
  );
  sky130_fd_sc_hd__conb_1 _42_ (
    .LO(mac_result[42])
  );
  sky130_fd_sc_hd__conb_1 _43_ (
    .LO(mac_result[43])
  );
  sky130_fd_sc_hd__conb_1 _44_ (
    .LO(mac_result[44])
  );
  sky130_fd_sc_hd__conb_1 _45_ (
    .LO(mac_result[45])
  );
  sky130_fd_sc_hd__conb_1 _46_ (
    .LO(mac_result[46])
  );
  sky130_fd_sc_hd__conb_1 _47_ (
    .LO(mac_result[47])
  );
  sky130_fd_sc_hd__conb_1 _48_ (
    .LO(mac_result[48])
  );
  sky130_fd_sc_hd__conb_1 _49_ (
    .LO(mac_result[49])
  );
  sky130_fd_sc_hd__conb_1 _50_ (
    .LO(mac_result[50])
  );
  sky130_fd_sc_hd__conb_1 _51_ (
    .LO(mac_result[51])
  );
  sky130_fd_sc_hd__conb_1 _52_ (
    .LO(mac_result[52])
  );
  sky130_fd_sc_hd__conb_1 _53_ (
    .LO(mac_result[53])
  );
  sky130_fd_sc_hd__conb_1 _54_ (
    .LO(mac_result[54])
  );
  sky130_fd_sc_hd__conb_1 _55_ (
    .LO(mac_result[55])
  );
  sky130_fd_sc_hd__conb_1 _56_ (
    .LO(mac_result[56])
  );
  sky130_fd_sc_hd__conb_1 _57_ (
    .LO(mac_result[57])
  );
  sky130_fd_sc_hd__conb_1 _58_ (
    .LO(mac_result[58])
  );
  sky130_fd_sc_hd__conb_1 _59_ (
    .LO(mac_result[59])
  );
  sky130_fd_sc_hd__conb_1 _60_ (
    .LO(mac_result[60])
  );
  sky130_fd_sc_hd__conb_1 _61_ (
    .LO(mac_result[61])
  );
  sky130_fd_sc_hd__conb_1 _62_ (
    .LO(mac_result[62])
  );
  sky130_fd_sc_hd__conb_1 _63_ (
    .LO(mac_result[63])
  );
  sky130_fd_sc_hd__conb_1 _64_ (
    .LO(spi_cs)
  );
  sky130_fd_sc_hd__conb_1 _65_ (
    .LO(spi_mosi)
  );
  sky130_fd_sc_hd__conb_1 _66_ (
    .LO(i2c_sda_out)
  );
  sky130_fd_sc_hd__conb_1 _67_ (
    .LO(gpio_out[0])
  );
  sky130_fd_sc_hd__conb_1 _68_ (
    .LO(gpio_out[1])
  );
  sky130_fd_sc_hd__conb_1 _69_ (
    .LO(gpio_out[2])
  );
  sky130_fd_sc_hd__conb_1 _70_ (
    .LO(gpio_out[3])
  );
  sky130_fd_sc_hd__conb_1 _71_ (
    .LO(gpio_out[4])
  );
  sky130_fd_sc_hd__conb_1 _72_ (
    .LO(gpio_out[5])
  );
  sky130_fd_sc_hd__conb_1 _73_ (
    .LO(gpio_out[6])
  );
  sky130_fd_sc_hd__conb_1 _74_ (
    .LO(gpio_out[7])
  );
  sky130_fd_sc_hd__conb_1 _75_ (
    .LO(timer_irq)
  );
  sky130_fd_sc_hd__conb_1 _76_ (
    .LO(mac_done)
  );
  sky130_fd_sc_hd__conb_1 _77_ (
    .LO(uart_tx)
  );
  sky130_fd_sc_hd__buf_2 _78_ (
    .A(clk),
    .X(i2c_scl)
  );
  sky130_fd_sc_hd__buf_2 _79_ (
    .A(clk),
    .X(spi_sclk)
  );
endmodule
